dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/ckanpackager/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.ckanpackager setup.py nosetests --ckan --with-pylons=ckanext/ckanpackager/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.ckanpackager --rednose

after_success: coveralls
